# Generated by Django 4.2.4 on 2023-08-28 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_friends', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Todo'), (1, 'Doing'), (2, 'Done')], default=0)),
                ('start_todo', models.DateTimeField(null=True)),
                ('end_todo', models.DateTimeField(null=True)),
                ('content', models.TextField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_app.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.user')),
            ],
        ),
    ]
