version: "3"

services:
  backend:
    depends_on:
      - db
    build:
      context: scheduler
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./scheduler:/app
    command: 
      - ./start.sh

  nginx:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: dockerfile.nginx
    ports:
      - "8888:80"
    env_file:
      - .env.local

  db:
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - .env.local
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
